services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_DATABASE: fact_checker_db
      MYSQL_USER: user
      MYSQL_PASSWORD: K630
      MYSQL_ROOT_PASSWORD: K630_2
    env_file:
      - ./database/.env
    volumes:
      - mariadb_data:/var/lib/mysql  # keeps data alive after container restarts
    # add ports only if running locally for development
    #ports:
    #  - "3306:3306"
    healthcheck:
      #for local development:
      #test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      #for server deployment:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5

  #api:
    #build: .
    #restart: always
    #env_file:
    #  - ./backend/.env
    #  - ./database/.env
    #ports:
    #  - "8000:8000"
    #depends_on:
    #  db:
    #    condition: service_healthy
    #command: gunicorn --bind 0.0.0.0:8000 app_root.wsgi:application
    #CMD ["fastapi", "dev", "application.py", "--host", "0.0.0.0"]

  web:
    build: .
    restart: always
    env_file:
      - ./database/.env
    working_dir: /app/database/app
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy


  tunnel:
    env_file:
      - ./database/.env
    image: cloudflare/cloudflared
    restart: always
    command: tunnel run --token ${TUNNEL_TOKEN}


volumes:
  mariadb_data: {}


  # leave this commented only for local development, comment out for server deployment
  #web:
  #   build: .
  #   env_file:
  #     - .env
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - ./app:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     db:
  #